# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af805f7b030d81bc2c025e01fc61132f0328962d19cac4ca96093f50188759aa986f9ad4153f8e8b88f645f834020d038300545f9f1832e84b5002657a54a98e

test:
  secret_key_base: 1d6f6fcb1265bf26836d75b19a1f616d2087f435bc1ea953498be427048e3f66f2e882239cdbcc5bd6d55ff9b01dfed54c64192cd2180f7fd92c120ffca3b588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
