# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ac6ed8f1f7aaedb8919ba712055c84787691f7375f74e7b51a2b1f7a1d1e3b7bb2949c47f0c871c085fa4fa4aa0169bd6c6ce4d3847e1cfc44b392c1edb06f

test:
  secret_key_base: cb1901e1e5bf004262e2b3b01cd02ad399cb5c519ccae36fb3141c0f6dedda3430d930d65b12c8b675c56bbc38d473872ba52575cf115574cb96472ebfdd46fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
