# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc948966634547f36c7698c399cd23d5b0ab30f89945fc64ca512fb3b396e3e43ce2b004afa4ca03628ed9c6bc76c24571cfc57b9cc821ff2745e60d1d4ba5a0

test:
  secret_key_base: 5595db96d73805c3fd724213e4a0dc6e47eb9ff4cf8da98dc80b7fce063a47449715e93ab24790c3a3a48c4b6bc5cc59b86bb914a1aad72627aa3f8f6cfa956a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
