# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34f4368554bdc0294bb7077efebe92fd00774f1c6decfd7657ee223b91bb0db0b4ef96976fff512933e4184ce3c92e4091861dbb776f0b83eba3a7dd0a126120

test:
  secret_key_base: 2d0344ad79485de3491cbd788ddc2e4caf659e4ddde42f3791618ae0b9690a11e5fb72ae189937063801c1010f378e3f59680b6246503af202687ae082a482c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
